version: "3.8"

volumes:
  postgres_data:

services:
  db:
    image: postgres:12.4
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432

  web:
    build: .
    restart: always
    command: uvicorn sql_app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env 
